name: Android CI - Build Release APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Instala Gradle con SDKMAN solo para poder generar el wrapper si no existe
      - name: Install Gradle (for wrapper)
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle --version

      # Crea gradlew/gradle-wrapper si falta en el repo
      - name: Generate Gradle wrapper if missing
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          if [ ! -f ./gradlew ]; then
            gradle wrapper --gradle-version 8.7
            chmod +x ./gradlew
          fi

      # Ahora que ya existe el wrapper, habilitamos caché de Gradle
      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # Compila el APK de release del módulo :app (ruta segura)
      - name: Build Release APK
        run: ./gradlew :app:assembleRelease

      # Sube cualquier APK generado en release
      - name: Upload Release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
