name: Android CI - Build Release APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Instalamos Gradle en el runner y lo usamos directamente (sin ./gradlew)
            - name: Build Release APK (:app)
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle assembleRelease -p app


      # (Opcional) ver estructura para depurar si algo no cuadra
      - name: Print tree
        run: |
          echo "Repo root content:"
          ls -la
          echo "app module content:"
          ls -la app || true

      # Compilar el APK de release del módulo :app
      - name: Build Release APK (:app)
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle :app:assembleRelease

      # Subir el artefacto generado
      - name: Upload Release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
