name: Android CI - Build Release APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Gradle 8.7
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle --version

      # Buscar automáticamente el build.gradle y compilar
      - name: Build Release APK
        run: |
          cd "$(dirname $(find . -name 'build.gradle' -o -name 'build.gradle.kts' | head -n 1))"
          gradle assembleRelease --warning-mode all

      - name: Upload Release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: "**/app-release.apk"
